### ISSUE TITLE
can not restore backup panel

### ISSUE THREAD

**Issue by aditya12311** [Ferks-FK/Pterodactyl-AutoThemes#12]
ERROR in resources/scripts/components/server/files/FileViewer.tsx:54:60
TS2322: Type '{ details: boolean; key: string; file: FileObject; }' is not assignable to type 'IntrinsicAttributes & { file: FileObject; }'.
  Property 'details' does not exist on type 'IntrinsicAttributes & { file: FileObject; }'.
    52 |                                     {
    53 |                                         sortFiles(files.slice(0, maxFiles)).map(file => (
  > 54 |                                             <FileObjectRow details={details} key={file.key} file={file}/>
       |                                                            ^^^^^^^
    55 |                                         ))
    56 |                                     }
    57 |                                     <MassActionsBar/>
error Command failed with exit code 2.

**Comment by Ferks-FK** [comment]
This is not a problem of the script.
Also, ask for support from the discord group.

**Comment by Katsuki0** [comment]
same issue
