### ISSUE TITLE
Says Flanco isnt compatible but it is.

### ISSUE THREAD

**Issue by sequoiadotdev** [Ferks-FK/Pterodactyl-AutoThemes#13]
![image](https://user-images.githubusercontent.com/102398177/171254204-bac6b55b-6189-4583-a1c8-96c4e35266c6.png)
![image](https://user-images.githubusercontent.com/102398177/171254279-54efc3f3-4ed7-43fa-9f87-de66570833cc.png)
![image](https://user-images.githubusercontent.com/102398177/171254288-0574ba2d-0307-4045-b51c-7f4d35c41262.png)

**Comment by Ferks-FK** [comment]
Check the [ChangeLog](https://github.com/Ferks-FK/Pterodactyl-AutoThemes/blob/main/CHANGELOG.md#v165).
