### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by n-tdi** [Ferks-FK/Pterodactyl-AutoThemes#15]
Possibility for themes to get updated to pterodactyl `1.9`?

**Comment by Ferks-FK** [comment]
> Possibility for themes to get updated to pterodactyl `1.9`?

Problem not related to the script.
As it has been said several times before, it is not only up to me to update the themes/addons, but also to their original authors.

**Comment by anondev-sudo** [comment]
So why you don't contact the authors? Who created dracula theme?

**Comment by Ferks-FK** [comment]
> So why you don't contact the authors? Who created dracula theme?

This is outside my scope of work, no one really knows who the author of this theme is.
