### ISSUE TITLE
 * ERROR: Incompatible Version!

### ISSUE THREAD

**Issue by BGDrew** [Ferks-FK/Pterodactyl-AutoThemes#19]
Hi is there an updated version of the themes 

thanks
![root](https://github.com/Ferks-FK/Pterodactyl-AutoThemes/assets/162998762/4a3b2609-324f-444f-ab28-03737522faca)
![panel](https://github.com/Ferks-FK/Pterodactyl-AutoThemes/assets/162998762/de1580d1-10ac-44c8-8b7c-7eb38f012d11)

**Comment by Ferks-FK** [comment]
It's not up to me or the script to update the themes, it's up to the authors.
