### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by finnie2006** [Ferks-FK/Pterodactyl-AutoThemes#4]
You forget to mention  notil for the dracula and enola them etc

**Comment by Ferks-FK** [comment]
Mention notil?
What problem is this related to?

**Comment by finnie2006** [comment]
none, but he made the theme sooo

**Comment by Ferks-FK** [comment]
Leave his github, I can add the credits.

**Comment by finnie2006** [comment]
The owner is fine with how it is like this
I will close the issue
